name: Ejercicio2

on: push

jobs:
 nose:
  runs-on: linux-latest
  permissions:
   security-events: write

  steps: 
   - name: accion
     uses: advanced-security/python-lint-code-scanning-action@v1
     with:
      linter: pylint
